version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/sample-jpa-multiproject/common"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/sample-jpa"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/sample-jdo"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/buildSrc"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/sample-jpa-multiproject/domain"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
