name: Java CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    name: Test on JDK ${{ matrix.jdk_version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # JDK matrix version
        jdk_version: [ '1.8', '9', '10', '11', '12', '13', '14' ]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.jdk_version }}
    - uses: actions/cache@master
      #Using master because of the multi-paths feature (reportedly only available on master at the moment)
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: cd buildSrc && ../gradlew build check jacocoTestReport --stacktrace


  publishLibrary:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 14

      - uses: actions/cache@master
        #Using master because of the multi-paths feature (reportedly only available on master at the moment)
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x ./buildSrc/gradlew

      - name: Publish to the Gradle Plugins Portal
        run: |
          cd buildSrc
          ../gradlew publishPlugins -Pgradle.publish.key="${{ secrets.GRADLE_PLUGINS_PUBLISH_KEY }}" -Pgradle.publish.secret="${{ secrets.GRADLE_PLUGINS_PUBLISH_SECRET }}"
